apiVersion: apps/v1
kind: Deployment
metadata:
    name: model-serve-api
    labels:
      app : model-serve-api
spec:
  selector:
    matchLabels:
      app: model-serve-api
  template:
    metadata:
      labels:
        app: model-serve-api
    spec:
      containers:
      - image: <path_to_your_image_here>
        imagePullPolicy: IfNotPresent
        name: model-serve-api
        env:
        - name: DAEMONSECS
          value: "15"
        - name: gitPath
          value: https://github.com/gyramais/models_serve.git
        - name: baseUrl
          value: models_serve
        - name: usergit
          value: vormenesse
        - name: password
          value: 
        command: ["/bin/bash"]
        args: ["-c","/etc/init.d/cron start && cd /app/app/ && python3 create_serve_models.py "]
